### PR TITLE
removed unused files/scripts and untracked useroptions

### PR DESCRIPTION
**Pull request by DanC123**
:bomb: Removed the files we didn't need, and the user options.

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
I assume the `.css` and font files are needed by the views?
Could `IUserRepository` get moved into the Repos dir?

**Comment by DanC123** [comment]
I suppose they aren't needed at the moment, I figured I would leave them in just so we had a basic look for the views. 

Is there any particular reason you'd want `IUserRepository` moved?

**Comment by st3v3nhunt** [comment]
Often, an interface will live alongside the class it is implementing (not always). Seen as there is a dir for the repository and the `UserRepository.cs` is in there it would be easier to find the interface if it was in the same dir.

**Comment by DanC123** [comment]
Done and squashed the commit.

**Comment by st3v3nhunt** [comment]
Lovely bubbly.

**Pull request merged**
