### PR TITLE
:wrench: Updated the minified release bootstrap file and reverted layout

### PR DESCRIPTION
**Pull request by jbroodie**

### CODE REVIEW

**Comment by DanC123** [comment]
Can we get some more variation in your emojis please, two spanners in a row is a bit bland

**Comment by st3v3nhunt** [comment]
@DanC123 becomes :cop:

**Comment by DanC123** [comment]
@st3v3nhunt I learned it all from you

**Comment by st3v3nhunt** [comment]
:older_man: :point_right: :man: :+1:

**Comment by jbroodie** [comment]
I'm not sure what the best practice in updating the css file is but this would force us to replicate any changes in either bootstrap file to both, doesn't seem quite right. Could require further investigation. @DanC123 This sounds like an exciting task for you seen as you broke it :wink: and love to criticize my emoji's :exclamation:

**Comment by DanC123** [comment]
@jbroodie I'd love to work on this but you already have a branch created and started looking in to it. It's no problem you can do it, I really don't mind. Feel free to take this off my hands, cheers. :koala:

**Comment by DanC123** [comment]
@jbroodie whats the reason for the using statement in the _layout.cshtml file?

**Comment by DanC123** [comment]
No longer relevant :x:

**Pull request closed without merging**
