### PR TITLE
Added missing route to the user controller on to the request url

### PR DESCRIPTION
**Pull request by jbroodie**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
:rotating_light: Emoji on the commit message please :smiling_imp:

**Comment by jbroodie** [comment]
:tada:

**Comment by DanC123** [comment]
:fireworks: such an important aspect :palm_tree:

**Comment by st3v3nhunt** [comment]
I was promised something *special* last time and although it might not be quite as good as a :monkey:, an emoji isn't half bad.

**Pull request merged**
