### PR TITLE
Added connection to database and intergration test for the api

### PR DESCRIPTION
**Pull request by jbroodie**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
@jbroodie Does this replace PR #30 ?

**Comment by jbroodie** [comment]
yea, do i just need to close the other?

**Comment by st3v3nhunt** [comment]
Ideally this would not be another PR, it would just be an iteration of the original one.
As it stands with this being a new PR the conversation on the previous one has been lost, in relation to this one.
What are the differences between this PR and PR #30?
Which bits of the feedback have been added and which not? Will they done in the future?

**Comment by st3v3nhunt** [comment]
@jbroodie I assume this is dead now?

**Comment by st3v3nhunt** [comment]
Closing this PR as #30 supersedes it.

**Pull request closed without merging**
