### PR TITLE
:godmode: Added and refactored some tests, codemaid solution-wide cleanu...

### PR DESCRIPTION
**Pull request by DanC123**
...p and removed .7z file from directory

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
Is there a config file for codemaid or are you just using the defaults?

**Comment by DanC123** [comment]
Defaults, seemed to do what I was looking for (mainly removing the extra spaces at the start of a line)

**Comment by st3v3nhunt** [comment]
OK. The build is queued atm, I'll my eye on it.

**Comment by DanC123** [comment]
While you eye on it, it seems that Johanthons fix hasn't worked anyway, still giving an error

**Comment by st3v3nhunt** [comment]
Time for some logging? :evergreen_tree: :hocho:

**Pull request merged**
